services:
  ops_lab:
    # hostname: ops_lab
    container_name: ops_lab
    image: ops_lab
    privileged: true
    working_dir: /apps/dev
    build:
      context: .
      dockerfile: Dockerfile
    # user: lab_user
    # user: "0:0" 
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command:
      - /bin/bash
      - -c
      - |
        tail -f
    volumes:
      - ./ops-framework:/repo/ops-framework
      - ./project-sample:/apps/dev/project-sample

  artifactory:
    build: ./artifactory
    container_name: artifactory
    ports:
      - "8082:8082"
    volumes:
      - ./artifactory:/app