services:
  ops_lab:
    # hostname: ops_lab
    container_name: ops_lab
    image: ops_lab
    privileged: true
    working_dir: /apps/dev
    build:
      context: .
      dockerfile: Dockerfile
    user: lab_user
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command:
      - /bin/bash
      - -c
      - |
        tail -f
    volumes:
      # - ../ops_framework:/project/ops_frameworks
      - ./ops-framework-linux:/project/ops_framework

  webrepo:
    image: nginx
    command: |
        bash -c "
        cp /conf/nginx.conf /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
        "
    volumes:
      - ./conf/nginx.conf:/conf/nginx.conf
      - ./local:/usr/share/nginx/html
    ports:
      - "8082:80"